### ISSUE TITLE
crypto-bigint

### ISSUE THREAD

**Issue by pinkforest** [rozbb/saber-rs#5]
Is there a reason crypto-bigint can't be used ? It would be great to have karatsuba there - I think it only had schoolbook atm

**Comment by rozbb** [comment]
We currently use Karatsuba

https://github.com/rozbb/saber-rs/blob/c028ffbb60b7826333d1a816e50fb5662e8f1be9/src/ring_arith.rs#L87-L88

I'm not sure bigint would be appropriate here, since integer multiplication actually differs a bit from the ring multiplication we have to do in this crate. In particular, N-limb * N-limb mult creates an N-limb ring element, not a 2N-limb ring element.

**Comment by pinkforest** [comment]
Yeah cool, my lack of reading :eyes: :sleeping:  thx
